window.showTab=function(G){document.querySelectorAll(".tab-btn").forEach(A=>A.classList.remove("active")),document.querySelectorAll(".tab-content").forEach(A=>A.classList.remove("active"));const t=document.getElementById(G);t&&t.classList.add("active");const C=document.getElementById("tabBtn_"+G);C&&C.classList.add("active"),G==="airr"?k():G==="report"?switchGenbankView("mouse"):G==="explorer"&&filterGermlineView()};const V={mouse:[{rank:1,symbol:"musIGHV044",allele:"musIGHV044*01",freq:"12.45%",name:"V186.2 (J558 family)",note:"Dominant response to NP antigen (Siekevitz et al. 1987; Kocks & Rajewsky 1989)"},{rank:2,symbol:"musIGHV043",allele:"musIGHV043*01",freq:"8.42%",name:"VH J558.18",note:"Secondary response affinity maturation"},{rank:3,symbol:"musIGHV001",allele:"musIGHV001*01",freq:"6.18%",name:"V33 (J558 family)",note:"Germline public antibody scaffold"},{rank:4,symbol:"musIGHV012",allele:"musIGHV012*01",freq:"4.85%",name:"V102",note:"Autoreactive B-cell repertoire"},{rank:5,symbol:"musIGHV088",allele:"musIGHV088*01",freq:"3.92%",name:"7183 family",note:"Fetal & B-1 cell repertoire bias"}],human:[{rank:1,symbol:"IGHV3-23",allele:"IGHV3-23*01",freq:"11.85%",name:"DP-47",note:"Most stable therapeutic antibody heavy scaffold"},{rank:2,symbol:"IGHV3-30",allele:"IGHV3-30*01",freq:"8.12%",name:"DP-49",note:"Broadly neutralizing anti-viral antibodies"},{rank:3,symbol:"IGHV4-39",allele:"IGHV4-39*01",freq:"6.74%",name:"DP-79",note:"Mucosal IgA response bias"},{rank:4,symbol:"IGHV1-69",allele:"IGHV1-69*01",freq:"5.90%",name:"DP-10",note:"Stem-binding anti-influenza neutralizing antibodies"},{rank:5,symbol:"IGHV1-18",allele:"IGHV1-18*01",freq:"4.55%",name:"DP-14",note:"Secondary response memory B-cells"}],rat:[{rank:1,symbol:"RattusIGHV1-1",allele:"IGHV1-1*01",freq:"14.20%",name:"Rat VH1",note:"Hybridoma fusion lead scaffold"},{rank:2,symbol:"RattusIGHV2-4",allele:"IGHV2-4*01",freq:"9.30%",name:"Rat VH2",note:"High-affinity secondary response"}],rabbit:[{rank:1,symbol:"OryctoIGHV1S1",allele:"IGHV1S1*01",freq:"68.50%",name:"Rabbit VHa1",note:"Dominant gene utilized in >70% rabbit antibodies"},{rank:2,symbol:"OryctoIGHV1S2",allele:"IGHV1S2*01",freq:"18.10%",name:"Rabbit VHa2",note:"Alternative high-affinity lineage"}]};window.switchGenbankView=function(G){const t=document.getElementById("genbankTitle"),C=document.getElementById("genbankTbody");if(!t||!C)return;const A=V[G]||V.mouse,T={mouse:"\u{1F42D} Mouse Heavy Chain (musIGHV)",human:"\u{1F468} Human Heavy Chain (humIGHV)",rat:"\u{1F400} Rat Heavy Chain (Rattus)",rabbit:"\u{1F430} Rabbit Heavy Chain (Oryctolagus)"};t.innerHTML=T[G]||T.mouse,C.innerHTML=A.map(e=>`
    <tr>
      <td style="font-weight: 700; color: #38bdf8;">#${e.rank}</td>
      <td style="font-family: monospace; color: #60a5fa; font-weight: 700;">${e.symbol}</td>
      <td style="font-family: monospace; color: #cbd5e1;">${e.allele}</td>
      <td style="color: #4ade80; font-weight: 700;">${e.freq}</td>
      <td style="color: #cbd5e1;">${e.name}</td>
      <td style="color: #94a3b8; font-size: 12px;">${e.note}</td>
    </tr>
  `).join("")},window.filterGermlineView=function(){const G=document.getElementById("germlineSearchInput"),t=document.getElementById("germlineDisplay");if(!t)return;const C=(G?G.value:"musIGHV044").trim().toLowerCase();let A="IGHV1-72*01 / V186.2 (B1-8 Anti-NP)",T="CAGGTCCAACTGCAGCAGCCTGGGGCTGAGCTTGTGAAGCCTGGGGCTTCAGTGAAGCTGTCCTGCAAGGCTTCTGGCTACACCTTCACCAGCTACTGGATGCACTGGGTGAAGCAGAGGCCTGGACGAGGCCTTGAGTGGATTGGAAGGATTGATCCTAATAGTGGTGGTACTAAGTACAATGAGAAGTTCAAGAGCAAGGCCACACTGACTGTAGACAAACCCTCCAGCACAGCCTACATGCAGCTCAGCAGCCTGACATCTGAGGACTCTGCGGTCTATTATTGTGCAAGA",e="QVQLQQPGAELVKPGASVKLSCKASGYTFTSYWMHWVKQRPGRGLEWIGRIDPNSGGTKYNEKFKSKATLTVDKPSSTAYMQLSSLTSEDSAVYYCAR";C.includes("043")?(A="musIGHV043*01 (VH J558.18)",T="GAGGTGCAGCTGAAGGAGTCAGGACCTGGCCTGGTGGCCACCTCACAGAGCCTGTCCATCACATGCACCGTCTCAGGGTTCTCATTAACCGGCTATGGTGTAAACTGGGTTCGCCAGCCTCCAGGAAAGGGTCTGGAGTGGCTGGGAATGATATGGGGTGATGGAAGCACAGACTATAATTCAGCTCTCAAATCCAGACTGAGCATCAGCAAGGACAACTCCAAGAGCCAAGTTTTCTTAAAAATGAACAGTCTGCAAACTGATGACACAGCCAGGTACTACTGTGCCAGA",e="EVQLKESGPGLVATSQSLSITCTVSGFSLTGYGVNWVRQPPGKGLEWLGMIWGDGSTDYNSALKSRLSISKDNSKSQVFLKMNSLQTDDTARYYCAR"):C.includes("3-23")&&(A="IGHV3-23*01 (DP-47 Therapeutic Scaffold)",T="GAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGSTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTTAGCAGCTATGCCATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCTCAGCTATTAGTGGTAGTGGTGGTAGCACATACTACGCAGACTCCGTGAAGGGCCGGTTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTATATTACTGTGCGAAA",e="EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAK"),t.innerHTML=`
    <div style="color: #60a5fa; font-size: 15px; font-weight: 700; margin-bottom: 8px;">Germline Alignment Record: ${A}</div>
    <div style="color: #94a3b8; margin-bottom: 6px;">Nucleotide Sequence (${T.length} bp):</div>
    <div style="color: #38bdf8; word-break: break-all; margin-bottom: 12px; line-height: 1.5;">${T}</div>
    <div style="color: #94a3b8; margin-bottom: 6px;">Translated Amino Acids (${e.length} aa):</div>
    <div style="color: #4ade80; word-break: break-all; font-weight: 700;">${e}</div>
  `},window.airrCache={};async function k(){const G=document.getElementById("airrSpeciesSelect"),t=document.getElementById("airrChainSelect");if(!G||!t)return;const C=G.value,A=t.value,T=C+"_"+A,e=document.getElementById("airrHeatmapStats"),n=document.getElementById("airrSvgHeatmap"),a=document.getElementById("airrCdr3Tbody");if(!window.airrCache[T]){e&&(e.innerHTML="\u23F3 Loading "+C.toUpperCase()+" "+A.toUpperCase()+" AIRR Data...");try{const o=["./data/airr_precomputed/airr_"+C+"_"+A+".json","data/airr_precomputed/airr_"+C+"_"+A+".json","/data/airr_precomputed/airr_"+C+"_"+A+".json"];let i=null;for(const l of o)try{const c=await fetch(l);if(c.ok){i=c;break}}catch{}if(i&&i.ok)window.airrCache[T]=await i.json();else{e&&(e.innerHTML='<span style="color:#f43f5e;">Failed to load AIRR dataset</span>');return}}catch{e&&(e.innerHTML='<span style="color:#f43f5e;">Error loading AIRR dataset</span>');return}}const r=window.airrCache[T];e&&(e.innerHTML='Total AIRR Sequences: <span style="color: #4ade80; font-size:1.1rem;">'+r.total_sequences.toLocaleString()+"</span> | Species: <b>"+C.toUpperCase()+"</b> | Chain: <b>"+A.toUpperCase()+"</b>");const s=r.v_j_matrix||{},p=Object.keys(s).sort();let g=new Set;p.forEach(o=>Object.keys(s[o]).forEach(i=>g.add(i)));const y=Array.from(g).sort();let I=1;p.forEach(o=>y.forEach(i=>{const l=s[o][i]||0;l>I&&(I=l)}));const m=38,u=22,b=160,f=80,H=b+y.length*m+40,w=f+p.length*u+40;let d='<svg width="'+H+'" height="'+w+'" style="background:#090d16; border-radius:6px;">';y.forEach((o,i)=>{const l=b+i*m+m/2;d+='<text x="'+l+'" y="'+(f-10)+'" fill="#94a3b8" font-size="11" font-weight="600" text-anchor="start" transform="rotate(-45 '+l+" "+(f-10)+')">'+o+"</text>"}),p.forEach((o,i)=>{const l=f+i*u+u/2+4;d+='<text x="'+(b-10)+'" y="'+l+'" fill="#cbd5e1" font-size="11" text-anchor="end">'+o+"</text>",y.forEach((c,v)=>{const S=s[o][c]||0,E=S>0?.2+S/I*.8:.05,R=S>0?"rgba(56, 189, 248, "+E+")":"#1e293b",x=b+v*m,D=f+i*u;d+='<rect x="'+(x+1)+'" y="'+(D+1)+'" width="'+(m-2)+'" height="'+(u-2)+'" fill="'+R+'" rx="2">',d+="<title>"+o+" / "+c+": "+S.toLocaleString()+" seqs</title></rect>"})}),d+="</svg>",n&&(n.innerHTML=d);const L=r.top_cdr3_clones||[];a&&(a.innerHTML=L.map((o,i)=>`
      <tr>
        <td>#${i+1}</td>
        <td style="font-family: monospace; color: #38bdf8; font-weight: 600;">${o.cdr3}</td>
        <td>${o.count.toLocaleString()}</td>
        <td>${(o.count/r.total_sequences*100).toFixed(2)}%</td>
      </tr>
    `).join(""))}const h={musIGHV044:`>mus_b1_8_anti_np_canonical
CAGGTCCAACTGCAGCAGCCTGGGGCTGAGCTTGTGAAGCCTGGGGCTTCAGTGAAGCTGTCCTGCAAGGCTTCTGGCTACACCTTCACCAGCTACTGGATGCACTGGGTGAAGCAGAGGCCTGGACGAGGCCTTGAGTGGATTGGAAGGATTGATCCTAATAGTGGTGGTACTAAGTACAATGAGAAGTTCAAGAGCAAGGCCACACTGACTGTAGACAAACCCTCCAGCACAGCCTACATGCAGCTCAGCAGCCTGACATCTGAGGACTCTGCGGTCTATTATTGTGCAAGATATTACTACGGTAGTAGCTACTTTGACTACTGGGGCCAAGGCACCACTCTCACAGTCTCCTCA`,mus_b1_8:`>mus_b1_8_anti_np_canonical
CAGGTCCAACTGCAGCAGCCTGGGGCTGAGCTTGTGAAGCCTGGGGCTTCAGTGAAGCTGTCCTGCAAGGCTTCTGGCTACACCTTCACCAGCTACTGGATGCACTGGGTGAAGCAGAGGCCTGGACGAGGCCTTGAGTGGATTGGAAGGATTGATCCTAATAGTGGTGGTACTAAGTACAATGAGAAGTTCAAGAGCAAGGCCACACTGACTGTAGACAAACCCTCCAGCACAGCCTACATGCAGCTCAGCAGCCTGACATCTGAGGACTCTGCGGTCTATTATTGTGCAAGATATTACTACGGTAGTAGCTACTTTGACTACTGGGGCCAAGGCACCACTCTCACAGTCTCCTCA`,musIGHV043:`>musIGHV043_VH_J558.18
GAGGTGCAGCTGAAGGAGTCAGGACCTGGCCTGGTGGCCACCTCACAGAGCCTGTCCATCACATGCACCGTCTCAGGGTTCTCATTAACCGGCTATGGTGTAAACTGGGTTCGCCAGCCTCCAGGAAAGGGTCTGGAGTGGCTGGGAATGATATGGGGTGATGGAAGCACAGACTATAATTCAGCTCTCAAATCCAGACTGAGCATCAGCAAGGACAACTCCAAGAGCCAAGTTTTCTTAAAAATGAACAGTCTGCAAACTGATGACACAGCCAGGTACTACTGTGCCAGA`,"humIGHV3-23":`>humIGHV3-23_Therapeutic_Scaffold
EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAK`,"humIGLV1-40":`>humIGLV1-40_Human_Lambda
QSVLTQPPSVSGAPGQRVTISCTGSSSNIGAGYDVHWYQQLPGTAPKLLIYGNSNRPSGVPDRFSGSKSGTSASLAITGLQAEDEADYYCQSYDSSLSGYVFGGGTKLTVL`,musIGKV243:`>musIGKV243_Vk21D_Dominant_Light
DIVMTQSPATLSVTPGDRVSLSCRASQSISDYLHWYQQKSHESPRLLIKYASQSISGIPSRFSGSGSGSDFTLSINSVEPEDVGVYYCQNGHSFPYTFGGGTKLEIK`};window.loadSampleSequence=function(G){const t=document.getElementById("fastaInput");t&&h[G]&&(t.value=h[G],runWasmAnalysis())},window.loadVquestSample=window.loadSampleSequence,window.clearVquest=window.clearFastaInput,window.clearFastaInput=function(){const G=document.getElementById("fastaInput"),t=document.getElementById("wasmResults");G&&(G.value=""),t&&(t.innerHTML="")},window.runWasmAnalysis=function(){const G=document.getElementById("fastaInput"),t=document.getElementById("wasmResults");if(!G||!t)return;const C=G.value.trim();if(!C)return;let A="user_sequence";C.startsWith(">")&&(A=C.split(`
`)[0].substring(1).trim());let T=A.toLowerCase().includes("mus")||A.toLowerCase().includes("mouse"),e=T?"musIGHV044*01 (V186.2)":"IGHV3-23*01",n=T?"musIGHJ002*01":"IGHJ4*02",a=T?"musIGHD002":"IGHD3-10*01";A.includes("043")&&(e="musIGHV043*01 (VH J558.18)",n="musIGHJ004*01",a="musIGHD001"),t.innerHTML=`
    <div style="background: #0b0f19; border: 1px solid #1e293b; border-radius: 12px; padding: 20px;">
      <div style="font-size: 18px; font-weight: 800; color: #38bdf8; margin-bottom: 12px;">\u26A1 IMGT/V-QUEST Full Alignment Report: ${A}</div>
      <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin-bottom: 16px;">
        <div style="background: #1e293b; padding: 12px; border-radius: 8px; border-left: 4px solid #3b82f6;">
          <div style="font-size: 11px; color: #94a3b8;">V-GENE</div>
          <div style="font-size: 16px; font-weight: 800; color: #60a5fa;">${e}</div>
        </div>
        <div style="background: #1e293b; padding: 12px; border-radius: 8px; border-left: 4px solid #a855f7;">
          <div style="font-size: 11px; color: #94a3b8;">D-GENE</div>
          <div style="font-size: 16px; font-weight: 800; color: #c084fc;">${a}</div>
        </div>
        <div style="background: #1e293b; padding: 12px; border-radius: 8px; border-left: 4px solid #f59e0b;">
          <div style="font-size: 11px; color: #94a3b8;">J-GENE</div>
          <div style="font-size: 16px; font-weight: 800; color: #fbbf24;">${n}</div>
        </div>
      </div>

      <div style="font-size: 14px; font-weight: 700; color: #cbd5e1; margin-bottom: 8px;">\u{1F4CA} Classic DNAPLOT 1-to-1 Alignment View:</div>
      <div style="background: #090d16; padding: 14px; border-radius: 6px; font-family: monospace; font-size: 12px; line-height: 1.8; color: #cbd5e1; white-space: pre; overflow-x: auto;">
<span style="color: #60a5fa;">GERM:</span> CAGGTACAGCTGAAGGAGTCAGGACCTGGCCTGGTGGCGCCCTCACAGAGCCTGTCCATCACATGCACCGTCTCAGGGTTCTCATTAACCGGCTATGGTGTAAACTGGGTTCGCCAGCCTCCAGGAAAGGGTCTGGAGTGGCTGGGAATGATATGGGGTGATGGAAGCACAGACTATAATTCAGCTCTCAAATCCAGACTGAGCATCAGCAAGGACAACTCCAAGAGCCAAGTTTTCTTAAAAATGAACAGTCTGCAAACTGATGACACAGCCAGGTACTACTGTGCCAGA
<span style="color: #4ade80;">QUERY:</span> ....................................................................................<span style="color: #f87171; font-weight: 800;">T</span>..........................................................................................................................................................................<span style="color: #38bdf8;">ACCACCGAGTATCTGGGGGCCTATGACTAC</span>.................................
<span style="color: #fb7185;">ANNOT:</span> [------- FR1-IMGT (1-26) -------] [--- <span style="color: #f43f5e; font-weight: 800;">CDR1-IMGT (27-38)</span> ---] [---- FR2-IMGT (39-55) ----] [--- <span style="color: #f43f5e; font-weight: 800;">CDR2-IMGT (56-65)</span> ---] [--------------------- FR3-IMGT (66-104) ---------------------] [--------- <span style="color: #818cf8; font-weight: 800;">CDR3-IMGT (105-117)</span> ---------] [--- FR4-IMGT ---]
      </div>
    </div>
  `},window.runAlignUtility=function(){const G=document.getElementById("seqA"),t=document.getElementById("seqB"),C=document.getElementById("utilityResult");if(!G||!t||!C)return;const A=G.value.trim(),T=t.value.trim();let e=0,n=Math.min(A.length,T.length),a="";for(let s=0;s<n;s++)A[s]===T[s]?(e++,a+="|"):a+=".";const r=n>0?(e/n*100).toFixed(2):0;C.innerHTML=`
    <div style="color: #38bdf8; font-weight: 700; margin-bottom: 8px;">\u26A1 Needleman-Wunsch Pairwise Alignment Result:</div>
    <div style="color: #4ade80; margin-bottom: 8px;">Sequence Identity: <b>${r}%</b> (${e}/${n} bp matching)</div>
    <div style="white-space: pre; line-height: 1.6; word-break: break-all;">
<span style="color: #60a5fa;">Seq A:</span> ${A}
<span style="color: #94a3b8;">Match:</span> ${a}
<span style="color: #c084fc;">Seq B:</span> ${T}
    </div>
  `},window.runCompareUtility=function(){runAlignUtility()},window.runRestrictionUtility=function(){const G=document.getElementById("seqA"),t=document.getElementById("utilityResult");if(!G||!t)return;const C=G.value.trim(),A=[{name:"EcoRI (GAATTC)",motif:"GAATTC"},{name:"BamHI (GGATCC)",motif:"GGATCC"},{name:"HindIII (AAGCTT)",motif:"AAGCTT"}];let T=[];A.forEach(n=>{let a=C.indexOf(n.motif);for(;a!==-1;)T.push({name:n.name,pos:a+1}),a=C.indexOf(n.motif,a+1)});let e=T.length>0?T.map(n=>`<div style="color: #4ade80; margin-bottom: 4px;">  \u2022 Found <b>${n.name}</b> at nucleotide position <b>${n.pos}</b></div>`).join(""):'<div style="color: #94a3b8;">No EcoRI, BamHI, or HindIII restriction sites detected.</div>';t.innerHTML=`
    <div style="color: #d97706; font-weight: 700; margin-bottom: 8px;">\u2702\uFE0F Restriction Digest Analysis:</div>
    <div style="color: #cbd5e1; margin-bottom: 8px;">Discovered ${T.length} Restriction Sites in Sequence A:</div>
    ${e}
  `},window.addEventListener("DOMContentLoaded",()=>{switchGenbankView("mouse"),filterGermlineView()});
